### PR TITLE
add typing + fix small issues

### PR DESCRIPTION
**Pull request by leo-schick**
Add typing for parameters + fix several small issues in code

### CODE REVIEW

**Review by jankatins — APPROVED** [review]
LGTM...

Whats the minimum py version? It might be already enough for regular `list[dict[str, str]]` like annotations and `x | None` instead of `Optiona[x]`... Oh well, at some point, a pyupgrade/ruff run will fix that :-)

**Comment by leo-schick** [comment]
@jankatins I paid attention that I don't use all the fancy new stuff becuase we still have 3.6 as minimum requirement. I dropped 3.6 from the CI tests because it isn't anymore supported (and CI tests are not available anymore).

I often hesitate to upgrade because I don't know what people use out there.
`x | None` requires 3.10. I am currently on 3.9 because of some package dependecies which where incompatible when I tried to upgrade the last time.

Any suggestions for a policy when we should upgrade python versions?

**Comment by jankatins** [comment]
I think I remember that the initial mara version had python requirement on the "latest and greatest python" :-)

Basically up to you, but my suggestion would be to at least drop anything which is not supported anymore. Given that everybody and my mother runs in a docker container that shouldn't be a big problem :-)

**Comment by leo-schick** [comment]
@jankatins Sounds great! I think I will merge this for now and we can apply this on e.g. next major release and make python 3.11 as a minimum requirement.

**Pull request merged**
